// 成果物データ（ここだけ更新すればサイトに反映される）
// cat: "宇宙" | "物性"   sub: "銀河" | "太陽系" | "星々の動き" | ""（詳細なし）
// yt : YouTube Shorts の video id（なければ ""）   note: 記事URL（なければ ""）
const articles = [
  {
    title: "銀河の形ひとつに、叡智が総動員されていた。",
    cat: "宇宙", sub: "銀河",
    summary: "真横から撮った銀河の写真は、ぞっとするほど薄い一本の線。なぜ星は平らな渦巻きに集まるのか。",
    note: "https://note.com/megatempa/n/nfc147396160a",
    yt: "aUgVd6Gk7-g",
    price: "free",
  },
  {
    title: "見えないくせに重要なダークマター、存在根拠はシンプルすぎる話",
    cat: "宇宙", sub: "銀河",
    summary: "同じ星を同じ速さで回す銀河を2つ並べる。片方はやがて外側から飛び散ってしまう。その差が示すもの。",
    note: "https://note.com/megatempa/n/n0fd52f9a4714",
    yt: "udpuMFGGk9U",
    price: "free",
  },
  {
    title: "「月まで地球30個分の距離」くらいアホっぽく簡単にすれば、僕にだってわかったぞ。",
    cat: "宇宙", sub: "太陽系",
    summary: "月を見上げても距離は正直わからない。地球を30個ならべると、月に届く。スケールを数えられる形に。",
    note: "https://note.com/megatempa/n/nc3175ac11ffa",
    yt: "IYbWiEvz25M",
    price: "free",
  },
  {
    title: "北斗七星は、「今だけの集合写真」でちょっと面白かった話",
    cat: "宇宙", sub: "星々の動き",
    summary: "北斗七星の七つが、そろって同じ方へ流れていく。あの形は今この時代だけの集合写真だった。",
    note: "https://note.com/megatempa/n/n397fb0cfc416",
    yt: "D7nmLMubzn8",
    price: "free",
  },
  {
    title: "太陽系は爆速で動く。それでも星座が変わらない、たった二つの理由",
    cat: "宇宙", sub: "星々の動き",
    summary: "北斗七星も夏の大三角も、去年と同じ場所に同じ形で戻ってくる。爆速で動いているのに、なぜ。",
    note: "https://note.com/megatempa/n/n06bc8fcd29ba",
    yt: "6wFl_6_vKTE",
    price: "free",
  },
  {
    title: "天動説と地動説の顛末が爽快すぎた話",
    cat: "宇宙", sub: "太陽系",
    summary: "天動説と地動説の決着を知っていますか。勝ち負けだけでは終わらない、その顛末。",
    note: "https://note.com/megatempa/n/neb237e0f0843",
    yt: "3WPoI9m4jJE",
    price: "free",
  },
  {
    title: "この宇宙で太陽すら、止まっていませんでした。「静止」はありうるか",
    cat: "宇宙", sub: "星々の動き",
    summary: "止まっているものを、一つでいいので思い浮かべてみてください。この宇宙に本当の静止はあるのか。",
    note: "https://note.com/megatempa/n/ne09cc12e2208",
    yt: "0H5VJFLoHVs",
    price: "free",
  },
  {
    title: "毎月、日食未遂が起きている",
    cat: "宇宙", sub: "太陽系",
    summary: "満月の夜、月のすぐ近くには地球の影がいる。毎月「未遂」で終わっている食の話。",
    note: "https://note.com/megatempa/n/na769a0995100",
    yt: "2cCojNeKjF0",
    price: "free",
  },
  {
    title: "「地球は宇宙の中心じゃない」の続きを、誰も教えてくれなかった",
    cat: "宇宙", sub: "太陽系",
    summary: "地球は太陽のまわりを回っている。そこで止まった知識の、その先の話。",
    note: "https://note.com/megatempa/n/nec0869edb8b2",
    yt: "",
    price: "free",
  },
  {
    title: "磁石をあつあつからキンキンに冷やして放置してみた",
    cat: "物性", sub: "",
    summary: "熱々の磁石はバラバラの向き。冷やしていくと、ある温度で一斉に向きがそろって磁石になる。相転移のシミュレーション。",
    note: "",
    yt: "vXKSLBJCTWI",
    price: "free",
  },
];
